### ISSUE TITLE
Feature Request : Modbus "Proxy"

### ISSUE THREAD

**Issue by p1ngb4ck** [danielkucera/esp8266-opendps#4]
Hi,
first of all thanks a lot for your work !
Do you think you could maybe implement some kind of a "modbus-proxy" function on another tcp port, translating the modbus protocol to opendps-protocol and back ?
I would really love to use sigrok and smuview in connection with my dps5005 with a wemos-d1. Unfortunately it only supports "stock" (or profimax) firmware and I would really like to stay on opendps.
Unfortunately my skills are by far not big enough to implement this myself, but it seems there are arduino libraries available, as well as documentation about the original rdtech dps modbus implementation.

**Comment by danielkucera** [comment]
Hi @p1ngb4ck , I am sorry but I have no capacity to implement this. I don't even use the device anymore.

**Comment by p1ngb4ck** [comment]
Hi @danielkucera np, thanks so much anyhow for all your work and getting back to me here. Issue can be closed here then, I will try to make sth up myself on a fork.
In case I should get sth useful working, I`d then leave a note here, so you could then forward ppl to the ongoing work in case there is some and you wish to do so =)
Best regards,
Oliver

**Comment by danielkucera** [comment]
Sure, thank you.
